#!/usr/bin/env bash
# Unified OWL Installer Script
# One-command installation for the full Unified OWL DNS Synergy system
#
# This script:
# - Installs Python dependencies
# - Sets up the owl_dns_synergy package
# - Configures environment variables
# - Installs required MCP servers
# - Sets up Prometheus metrics
# - Installs NadirClaw for cost-optimized routing
# - Configures Caddy/TLS auto-configuration
# - Sets up bulk credential management
#
# Author: marktantongco
# Version: 1.1.3

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# ============================================
# Step 1: System Requirements Check
# ============================================
check_requirements() {
    log_info "Checking system requirements..."

    # Check Python version
    PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
    PY_MAJOR=$(echo "$PYTHON_VERSION" | cut -d. -f1)
    PY_MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)

    if [[ "$PY_MAJOR" -lt 3 ]] || {{ "$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 11 ]]; then
        log_error "Python 3.11+ required. Found: $PYTHON_VERSION"
        exit 1
    fi

    log_info "Python $PYTHON_VERSION - OK"

    # Check pip
    if ! command -v pip &> /dev/null; then
        log_error "pip not found. Install pip first."
        exit 1
    fi
    log_info "pip - OK"

    # Check git
    if ! command -v git &> /dev/null; then
        log_error "git not found. Install git first."
        exit 1
    fi
    log_info "git - OK"

    # Check curl/wget
    if ! command -v curl &> /dev/null && ! command -v wget &> /dev/null; then
        log_error "Either curl or wget is required."
        exit 1
    fi
    log_info "Download tool - OK"
}

# ============================================
# Step 2: Install Python Dependencies
# ============================================
install_dependencies() {
    log_info "Installing Python dependencies..."

    # Upgrade pip
    pip install --upgrade pip setuptools wheel 2>&1 | tail -1

    # Install core dependencies from requirements
    if [ -f "requirements.txt" ]; then
        pip install -r requirements.txt 2>&1 | tail -5
    else
        # Install core dependencies inline
        pip install httpx prometheus_client dataclasses 2>&1 | tail -5
    fi

    # Install owl_dns_synergy in development mode
    pip install -e . 2>&1 | tail -5

    log_info "Dependencies installed successfully"
}

# ============================================
# Step 3: Configure Environment Variables
# ============================================
setup_environment() {
    log_info "Setting up environment variables..."

    # Check if .env exists
    if [ -f ".env" ]; then
        log_info ".env file already exists, skipping..."
        return
    fi

    # Create .env from template
    cat > .env << 'EOF'
# Unified OWL Environment Configuration
# Generated by install.sh v1.1.3

# OWL DNS Synergy Configuration
OWL_PORT=60000
OWL_API_PORT=60001
OWL_GATEWAY_PORT=60010

# NadirClaw Cost Optimization
NADIRCLAW_BASE_URL=http://localhost:8856/v1
NADIRCLAW_MODEL=nadirclaw/auto

# Prometheus Metrics
PROMETHEUS_PORT=9090

# Redis (optional - for persistent caching)
REDIS_URL=redis://localhost:6379
USE_REDIS=false

# DNS Configuration
DNS_PORT=53
DNS_OVERRIDE_PORT=5353

# Key Rotation (OpenRouter)
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}

# Freebuff Configuration
FREEBUFF_UNIFIED_PORT=8080

# Logging
LOG_LEVEL=INFO
EOF

    log_info ".env file created"
    log_warn "Please review and edit .env with your actual API keys"
}

# ============================================
# Step 3: Install System Services
# ============================================
install_services() {
    log_info "Installing system services..."

    # Start Prometheus metrics server
    log_info "Starting Prometheus on port $PROMETHEUS_PORT..."
    nohup python3 -c "from prometheus_client import start_http_server; start_http_server($PROMETHEUS_PORT)" > /dev/null 2>&1 &

    # Start OWL DNS Synergy CLI
    log_info "Starting OWL DNS Synergy on port $OWL_PORT..."
    nohup python3 -m owl_dns_synergy.cli serve --host 127.0.0.1 --port $OWL_PORT > /tmp/owl-dns.log 2>&1 &

    # Wait for services to start
    sleep 3

    # Verify services are running
    if curl -s http://127.0.0.1:$OWL_PORT/health > /dev/null 2>&1; then
        log_info "OWL DNS Synergy is running on port $OWL_PORT"
    else
        log_warn "OWL DNS Synergy may still be starting. Check /tmp/owl-dns.log"
    fi
}

# ============================================
# Step 4: Install NadirClaw
# ============================================
install_nadirclaw() {
    log_info "Installing NadirClaw for cost-optimized routing..."

    # Check if nadirclaw is already installed
    if pip show nadirclaw > /dev/null 2>&1; then
        log_info "NadirClaw already installed"
    else
        log_info "Installing NadirClaw..."
        pip install nadirclaw 2>&1 | tail -3
    fi

    # Start nadirclaw server
    if ! curl -s http://localhost:8856/v1/health > /dev/null 2>&1; then
        log_info "Starting NadirClaw server..."
        nohup nadirclaw serve > /tmp/nadirclaw.log 2>&1 &
        sleep 2

        if curl -s http://localhost:8856/v1/health > /dev/null 2>&1; then
            log_info "NadirClaw is running on port 8856"
        else
            log_warn "NadirClaw may still be starting. Check /tmp/nadirclaw.log"
        fi
    else
        log_info "NadirClaw already running on port 8856"
    fi
}

# ============================================
# Step 5: Configure MCP Servers
# ============================================
configure_mcp() {
    log_info "Configuring MCP servers..."

    # Check opencode.jsonc for MCP configuration
    if [ -f "opencode.jsonc" ]; then
        # Ensure owl_dns_synergy is disabled (it's DNS tunneling, not MCP)
        if grep -q "owl_dns_synergy" opencode.jsonc; then
            # Mark as not MCP
            sed -i 's/"enabled": true/"enabled": false/' opencode.jsonc 2>/dev/null || log_warn "Could not modify opencode.jsonc"
            log_info "Set owl_dns_synergy as non-MCP (DNS tunneling server)"
        fi
    fi

    # Ensure owl_resilient is enabled
    if [ -f "opencode.jsonc" ]; then
        if ! grep -q "owl_resilient" opencode.jsonc; then
            # Add owl_resilient MCP configuration
            cat >> opencode.jsonc << 'EOF'

# owl_resilient MCP server (enabled)
"owl_resilient": {
  "type": "local",
  "command": ["python3", "-m", "owl_resilient.mcp"],
  "enabled": true,
  "cwd": "/home/x3/workspace/unified-owl",
  "description": "Resilient MCP server with 26 tools including github, headroom, octocode"
}
EOF
            log_info "Added owl_resilient MCP configuration"
        fi
    fi
}

# ============================================
# Step 6: Verify Installation
# ============================================
verify_installation() {
    log_info "Verifying installation..."

    # Check all imports work
    python3 -c "
import sys
sys.path.insert(0, '.')
from owl_dns_synergy.router import SmartChannelRouter
from owl_dns_synergy.dashboard import create_dashboard
from owl_dns_synergy.caddy_tls import generate_caddyfile
from owl_dns_synergy.bulk_credential_api import get_bulk_credential_manager
print('All imports successful')
" 2>&1 | tail -5

# Verify owl_dns_synergy is running
if curl -s http://127.0.0.1:60000/health > /dev/null 2>&1; then
    log_info "OWL DNS Synergy proxy: HEALTHY on port 60000"
else
    log_warn "OWL DNS Synergy proxy: not responding on port 60000"
fi

# Check NadirClaw
if curl -s http://localhost:8856/v1/health > /dev/null 2>&1; then
    log_info "NadirClaw: HEALTHY on port 8856"
else
    log_warn "NadirClaw: not responding on port 8856"
fi

log_info "Installation verification complete"
}

# ============================================
# Main Installation Flow
# ============================================
main() {
    echo ""
    echo "============================================"
    echo "  Unified OWL Installer v1.1.3"
    echo "  Comprehensive DNS Synergy & AI Router"
    echo "============================================"
    echo ""

    # Run all steps
    check_requirements
    echo ""
    install_dependencies
    echo ""
    setup_environment
    echo ""
    install_services
    echo ""
    install_nadirclaw
    echo ""
    configure_mcp
    echo ""
    verify_installation
    echo ""

    echo "============================================"
    echo "  Installation Complete!"
    echo "============================================"
    echo ""
    echo "Next steps:"
    echo "1. Review and edit .env with your API keys"
    echo "2. Run 'python3 -m owl_dns_synergy.dashboard' for TUI dashboard"
    echo "2. Visit http://localhost:60000 for proxy status"
    echo "3. Visit http://localhost:8856 for NadirClaw routing"
    echo ""
}

# Run main function
main "$@"